{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.dataformat",
    "module": "jackson-dataformat-toml",
    "version": "2.15.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.15.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-dataformat-toml-2.15.4.jar",
          "url": "jackson-dataformat-toml-2.15.4.jar",
          "size": 54683,
          "sha512": "82246296350e6df5e5bf7b1b13acdbfebd0fd9023caf24d9ea8caaf1bff77dac225309dd182483adf847182a3dcac0973173fc5b0801e0cc6a18a7999a0d53e5",
          "sha256": "395ffb92a06e84fb020fe7e0bb460c319e13b24e72c40ecd5334a8c9629b5e52",
          "sha1": "ead1098c1ad6368acc74407f0bee730debb4066f",
          "md5": "b7d1425e8064c0c97615c59138488e1a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.15.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-dataformat-toml-2.15.4.jar",
          "url": "jackson-dataformat-toml-2.15.4.jar",
          "size": 54683,
          "sha512": "82246296350e6df5e5bf7b1b13acdbfebd0fd9023caf24d9ea8caaf1bff77dac225309dd182483adf847182a3dcac0973173fc5b0801e0cc6a18a7999a0d53e5",
          "sha256": "395ffb92a06e84fb020fe7e0bb460c319e13b24e72c40ecd5334a8c9629b5e52",
          "sha1": "ead1098c1ad6368acc74407f0bee730debb4066f",
          "md5": "b7d1425e8064c0c97615c59138488e1a"
        }
      ]
    }
  ]
}
