spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    user:
      name: ${APP_USER}
      password: ${APP_PASSWORD}
logging:
  level:
    root: WARN
server:
  port: 8080
