spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/strategic_city_simulator
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: local
      password: localpass
logging:
  level:
    root: DEBUG
server:
  port: 8080
