name: Task - T1-3
description: κµ¬μ„± λ¶„λ¦¬
title: "[T1-3] κµ¬μ„± λ¶„λ¦¬"
labels: ["task"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## π“‹ Task κ°μ”
        `application-{local,dev,prod}.yaml`, ν”„λ΅ν•„λ³„ DB/λ΅κΉ…/λ³΄μ•.
        
        **DOD**
        - [ ] λ΅μ»¬/ν”„λ΅λ“ ν”„λ΅ν•„ μ¤μ„μΉ­ ν…μ¤νΈ
        
        ---
        
        ### [T2-1] μ§€ν‘ μ—…λ°μ΄νΈ ν¬λ®¬λ¬ λ¨λ“
        **λ‚΄μ©**
        - `IndicatorEngine` μΈν„°νμ΄μ¤ + κΈ°λ³Έ κµ¬ν„(ν¬μν¨μ¨/μμ—°λ³€ν™”/μƒνΈμ‘μ© νλΌλ―Έν„° μ£Όμ…).

  - type: textarea
    id: deliverables
    attributes:
      label: π“¦ μ‚°μ¶λ¬Ό
      value: |
        - μ„λΉ„μ¤/μ λ‹› ν…μ¤νΈ.

  - type: checkboxes
    id: dod
    attributes:
      label: β… Definition of Done
      options:
        - label: λ‹¨μ„ ν…μ¤νΈλ΅ κ³µμ‹ κ²€μ¦(μμƒκ°’ Β±μ¤μ°¨)
