name: Task - T1-3
description: 구성 분리
title: "[T1-3] 구성 분리"
labels: ["task"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 📋 Task 개요
        `application-{local,dev,prod}.yaml`, 프로필별 DB/로깅/보안.
        
        **DOD**
        - [ ] 로컬/프로드 프로필 스위칭 테스트
        ---
  - type: textarea
    id: deliverables
    attributes:
      label: 📦 산출물
      value: |
        - 서비스/유닛 테스트.

  - type: checkboxes
    id: dod
    attributes:
      label: ✅ Definition of Done
      options:
        - label: 단위 테스트로 공식 검증(예상값 ±오차)
