name: Task - T2-2
description: 상호작용 매트릭스 모듈
title: "[T2-2] 상호작용 매트릭스 모듈"
labels: ["task"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 📋 Task 개요
        카테고리 간 영향도 행렬 로딩( YAML/JSON ).

  - type: textarea
    id: deliverables
    attributes:
      label: 📦 산출물
      value: |
        - (해당 없음)

  - type: checkboxes
    id: dod
    attributes:
      label: ✅ Definition of Done
      options:
        - label: 샘플 매트릭스 로딩 및 적용 테스트

