name: Task - T3-1
description: 세션 시작 API
title: "[T3-1] 세션 시작 API"
labels: ["task"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 📋 Task 개요
        `POST /api/v1/sessions` (난이도/프리셋).

  - type: textarea
    id: deliverables
    attributes:
      label: 📦 산출물
      value: |
        - (해당 없음)

  - type: checkboxes
    id: dod
    attributes:
      label: ✅ Definition of Done
      options:
        - label: 201 Created & 초기 지표 반환
        - label: OpenAPI 명세 포함

