name: Task - T4-2
description: New Game Dialog 구성
title: "[T4-2] New Game Dialog 구성"
labels: ["task"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 📋 Task 개요
        난이도와 초기 상태를 선택하여 GameSession을 시작할 수 있는 다이얼로그 구성.

  - type: textarea
    id: deliverables
    attributes:
      label: 📦 산출물
      value: |
        - (해당 없음)

  - type: checkboxes
    id: dod
    attributes:
      label: ✅ Definition of Done
      options:
        - label: 시작 기능 구현
        - label: 취소 기능 구현

  - type: markdown
    attributes:
      value: |
        ## 🔌 연관 API
        - `POST /api/v1/sessions` (세션 시작)

        ## 🔗 참고
        - 와이어프레임: `docs/wireframes/figma/New_Game_Dialog.svg`
        - PRD: `PRD_expanded.md`
