name: Task - T5-3
description: ë¶€í•˜ í…ŒìŠ¤íŠ¸(ê°€ë²¼ìš´)
title: "[T5-3] ë¶€í•˜ í…ŒìŠ¤íŠ¸(ê°€ë²¼ìš´)"
labels: ["task"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## ðŸ“‹ Task ê°œìš”
        k6 or JMeterë¡œ ê°„ë‹¨ RPS, 95p ì§€ì—° < 200ms(ì‹œë®¬ë ˆì´íŠ¸).

  - type: textarea
    id: deliverables
    attributes:
      label: ðŸ“¦ ì‚°ì¶œë¬¼
      value: |
        - (í•´ë‹¹ ì—†ìŒ)

  - type: checkboxes
    id: dod
    attributes:
      label: âœ… Definition of Done
      options:
        - label: ë¦¬í¬íŠ¸ ì•„ì¹´ì´ë¸Œ

