name: Task - T9-2
description: 난이도 프리셋 편집 UI
title: "[T9-2] 난이도 프리셋 편집 UI"
labels: ["task"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 📋 Task 개요
        (세부 내용 미정 — tasklist.md 기준 초기 템플릿)

