CREATE TABLE game_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    difficulty VARCHAR(255),
    current_month INTEGER,
    created_at TIMESTAMP
);

CREATE TABLE event_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(255),
    description TEXT,
    occurred_at TIMESTAMP,
    session_id BIGINT NOT NULL REFERENCES game_sessions(id)
);

CREATE TABLE category_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(255),
    score INTEGER,
    session_id BIGINT NOT NULL REFERENCES game_sessions(id)
);

CREATE TABLE budget_allocations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(255),
    ratio DOUBLE PRECISION,
    session_id BIGINT NOT NULL REFERENCES game_sessions(id)
);

CREATE TABLE indicators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    metric_value INTEGER,
    session_id BIGINT NOT NULL REFERENCES game_sessions(id)
);

